name: "Accessibility Support Request (CAIA)"
description: "Request accessibility help from the content, accessibility, IA support team"
title: "[CAIA A11y Support]: Team name, product name"
labels: ["508/Accessibility, sitewide CAIA, sitewide accessibility, CAIA-a11y-support"]
assignees: [coforma-terry]
body:
- type: markdown
  attributes:
    value: "## Before we begin, is this work going through the collaboration cycle now?"
- type: markdown
  attributes:
    value: |
      If so, [use this ticket instead](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Sitewide+Content%2C+RLHecht&labels=sitewide+content%2C+sitewide+content-product+support&template=sitewide-content-intake-form.md&title=%3CType+of+Request%3E+from+%3CTeam%3E)
      Otherwise, if this is a request for help outside of the collaboration cycle, continue on ✨ 

- type: markdown
  attributes:
    value: "## What can we help you with?"
- type: markdown
  attributes:
    value: |
     We can offer several kinds of accessibility support based on your needs, including, but not limited to:
       - Reviewing your designer's mockups and prototypes
       - Training or upskilling your team's accessibility skills through workshops or assistive technology demos
       - Answering complex or wicked accessibility questions
       - Providing maintenance audits for products that haven't been reviewed in over 2 years
       - And more!
       
- type: textarea
  id: support-type
  attributes:
    label: What do you need support with?
    description: The more you can describe your need, the better we can take action to help y'all out!
    value: |
      ...
  validations:
    required: true       
    
- type: input
  id: timeframe
  attributes:
    label: When do you need this support by?
  validations:
    required: true
    
- type: dropdown
  id: urgency
  attributes:
    label: How urgent is this request?
    description: This will help us prioritize our work
    options:
      - Not urgent, we can use this help when CAIA has the time and resources
      - A little urgent, we need this support before the date we provided above
      - Very urgent, this is blocking other critical work and is needed ASAP
  validations:
    required: true
    
- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts (if any)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](Insert URL here between the parenthesis)
      - [User flows](Insert URL here between the parenthesis)
      - [Prototype or mockups](Insert URL here between the parenthesis)
      - [Epics/issue that may be helpful](Insert URL here between the parenthesis)
      - Anything else y'all think is important to share! Make sure to use the github link convention so it's accessible. Please avoid pasting direct URLS.
      ...
  validations:
    required: true

- type: markdown
  attributes:
    value: "## Your team's information"
- type: textarea
  id: team
  attributes:
    label: Who's on your team?
    description: This will help us reach out to you if needed
    value: |
      Team name:
      OCTO-DE product owner:
      Product manager:
      Designer:
      FE engineer:
      Product/team Slack channel:
      ...
  validations:
    required: true

- type: dropdown
  id: champion-1
  attributes:
    label: Do you have an accessibility champion on your team?
    description: If you don't have one, totally ok! Let us know if you're interested in becoming one.
    options:
      - No, we don't have a champion (yet)
      - No, but we are interested in training one!
      - Yes, we have a champion
  validations:
    required: true

- type: input
  id: champion-2
  attributes:
    label: If you have an accessibility champion, what's their name?
    description: We'll aim to partner with them if they have time.
  validations:
    required: false
    
- type: input
  id: champion-3
  attributes:
    label: Is anyone on your team interested in becoming an accessibility champion?
    description: We'll reach out to them separately to get them started on their journey!
  validations:
    required: false
    
- type: markdown
  attributes:
    value: "## Next steps"
    
- type: markdown
  attributes:
    value: |
      - [ ] [Your team]: Post a link to this ticket in the #accessibility-help Slack channel and tag Terry Nichols.
      - [ ] [CAIA]: Inform your team on when and how we can support this work.
      - [ ] [Your team]: Post support, fill out this optional feedback form to let us know how we can support y'all better into the future.
