name: "[DRAFT] Sitewide Content, Accessibility, and IA Intake Form"
description: "To request support with content, accessibility, or IA from Sitewide Content, Accessibility, and IA team. If this doesn’t look right, choose a different type."
title: "[CAIA Intake]: Team name, product name, type of request"
labels: ["sitewide CAIA, sitewide accessibility, sitewide content, epic"]
assignees: [coforma-terry, rlhecht]
body:
- type: markdown
  attributes:
    value: "## Support details"

- type: checkboxes
  id: type
  attributes:
    label: What does your team need support for? 
    description: Check all that apply.
    options:
      - label: Launching one or more unauthenticated pages, online forms, apps, or tools on VA.gov
      - label: Making revisions to one or more existing VA.gov pages
      - label: Something else
  validations:
    required: true

- type: textarea
  id: describe
  attributes:
    label: Describe what your team needs support with
    description: This can be a short description, but the more we know, the better we can serve y'all
    value: |
      ...
  validations:
    required: true


- type: checkboxes
  id: incremental
  attributes:
    label: Will this new product be released incrementally?
    description: For example, 25% of users initially. If you check yes, we'll reach out to discuss details about the content in the react widget.
    options:
      - label: Yes, we'll be launching incrementally
      - label: No, we won't
  validations:
    required: true
    
- type: input
  id: release
  attributes:
    label: When do you expect to launch your product to 100% of users?
    description: Please provide an estimated date so our team can create other relevant tickets.
  validations:
    required: true

- type: textarea
  id: artifacts
  attributes:
    label: Supporting artifacts (if any)
    description: If relevant, please provide supporting artifacts as available
    value: |
      - [Product outline](Insert URL here between the parenthesis)
      - [User flows](Insert URL here between the parenthesis)
      - [Prototype or mockups](Insert URL here between the parenthesis)
      - [Research plan](Insert URL here between the parenthesis)
      - [Research conversation guide](Insert URL here between the parenthesis)
      - [Epics/issue that may be helpful](Insert URL here between the parenthesis)
      ...
  validations:
    required: true

- type: checkboxes
  id: collab-cycle
  attributes:
    label: Will this be going through the collaboration cycle?
    options:
      - label: Yes, it will be going through the collaboration cycle
      - label: No, it will not
  validations:
    required: true

- type: textarea
  id: deadline
  attributes:
    label: When does this work need to be done?
    value: |
      - Estimated launch date:
      - Estimated staging review date:
      - Content, Accessibility, and IA work needed by:
      ...
  validations:
    required: true

- type: checkboxes
  id: office-hours
  attributes:
    label: Do you plan to bring this to an upcoming content office hours session?
    description: If we think this work would benefit from a collaborative session with you, we may ask you to bring it to office hours or set up a separate time to meet.
    options:
      - label: Yes, benefit content office hours (Thursdays, 3:00 p.m. to 3:45 p.m. ET)
      - label: Yes, health content office hours (Thursdays, 11:00 a.m. to 11:30 a.m. ET)
      - label: Yes, unauth office hours (Mondays, 11:00 a.m. to 11:30 a.m. ET)
      - label: No, but I'd like to schedule time to talk about this request
      - label: No, let's work asynchronously and meet if needed
  validations:
    required: true

- type: markdown
  attributes:
    value: "## Your team's information"
- type: textarea
  id: team
  attributes:
    label: Who's on your team?
    description: This will help us reach out to you if needed
    value: |
      Team name:
      OCTO-DE product owner:
      Product manager:
      Designer:
      FE engineer:
      Product/team Slack channel:
      ...
  validations:
    required: true

- type: dropdown
  id: champion-1
  attributes:
    label: Do you have an accessibility champion on your team?
    description: If you don't have one, totally ok! Let us know if you're interested in becoming one.
    options:
      - No, we don't have a champion (yet)
      - No, but we are interested in training one!
      - Yes, we have a champion
  validations:
    required: true

- type: input
  id: champion-2
  attributes:
    label: If you have an accessibility champion, what's their name?
    description: We'll aim to partner with them if they have time.
  validations:
    required: false
    
- type: input
  id: champion-3
  attributes:
    label: Is anyone on your team interested in becoming an accessibility champion?
    description: We'll reach out to them separately to get them started on their journey!
  validations:
    required: false
    
- type: markdown
  attributes:
    value: "## Next steps"
    
- type: markdown
  attributes:
    value: |
      - Once you’ve submitted this ticket, please post a link to this issue in the #sitewide-content-ia Slack channel and tag Randi Hecht.
      - Convert this issue into an Zenhub epic
      - If you also need engineering support from the Public Websites team, [fill out their intake request form](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=Public+Websites%2C+Sitewide+content&labels=vsa-public-websites%2C+vsa%2C+vsa-public-websites-intake%2C+sitewide-content%2C+needs-grooming&template=public-websites-intake.md&title=%3CType+of+Request%3E+from+%3CTeam%3E.)
      - If you need a page/URL redirected, a URL changed or a vanity URL set up, [please submit a Redirect, URL change, or vanity URL request](https://github.com/department-of-veterans-affairs/va.gov-team/issues/new?assignees=mnorthuis&labels=ia&template=redirect-request.md&title=Redirect+Request.)
